[base]
name = "tracke" # The FlowUnit name 
device = "cpu" # The device the flowunit runs on,cpu,cuda,ascend
version = "1.0.0" # The version of the flowunit
description = "A flowunit for modelbox" # The description of the flowunit
group_type = "generic" # flowunit group attribution 
type = "c++" # Fixed value


[config]
frame_rate = 30.0

# Input ports description
[input]
[input.input1]
name = "input_data"


# Output ports description
[output]
[output.output1]
name = "output_data"


