[base]
name = "business_processing_tusou" # The FlowUnit name 
device = "cpu" # The device the flowunit runs on,cpu,cuda,ascend
version = "1.0.0" # The version of the flowunit
description = "A flowunit for modelbox" # The description of the flowunit
group_type = "generic" # flowunit group attribution 
entry = "business_processing_tusou@Business_processing_tusouFlowUnit" # Python flowunit entry function
type = "python" # Fixed value

#stream = true
#normal = true

#condition = true
#expand = true
#collapse = true

[config]
output_broker_config = "/userdata/wm/code/modelbox-app/car-rk-test/src/graph-dev-test/webhook-wxs-config.json"
draw_results = false
save_results = false

# Input ports description
[input]
[input.input1]
name = "input_data"


# Output ports description
[output]
[output.output1]
name = "out_event_data"
[output.output2]
name = "out_object_data"
