
[driver]
dir = [
"/home/wm/code/modelbox-app/car-rk-test/src/flowunit",
"/home/wm/code/modelbox-app/car-rk-test/build/src/flowunit/tracke"
]
skip-default = false


[profile]
performance=false # 启用performance
trace=true # 启用traceing
dir="/home/wm/modelbox-perf/perf-video" # 设置跟踪文件路径


[flow]
desc = "car detection for video streams"

[graph]
graphconf = """
digraph car_detection {
    node [shape=Mrecord]
    video_input [ type=flowunit flowunit=video_input device=cpu deviceid="0" source_url="/home/wm/test-video/test-1.mp4" ]
    #video_input [ type=flowunit flowunit=video_input device=cpu deviceid="0" source_url="/home/wm/code/modelbox-app/car-rk-test/src/graph-dev-test/car_test_video.mp4" ]
    videodemuxer [ type=flowunit flowunit=video_demuxer device=cpu deviceid="0" ]
    videodecoder [ type=flowunit flowunit=video_decoder device=rockchip deviceid="0" pix_fmt=rgb ]
    img_resize [ type=flowunit flowunit=resize device=cpu image_height="640" image_width="640" interpolation=inter_linear ]
    yolov5_car_detect_rk [ type=flowunit flowunit=yolov5_car_detect_rk device=rockchip batch_size="1" queue_size="1" core_mask_id="2" ]
    yolov5_car_detect_post [ type=flowunit flowunit=yolov5_car_detect_post device=cpu batch_size="1" queue_size="1"]
    tracke [ type=flowunit flowunit=tracke device=cpu batch_size="1"  queue_size="1"]
    expand_car_boxes [ type=flowunit flowunit=expand_box device=cpu batch_size="1" queue_size="1"]
    car_resize [ type=flowunit flowunit=resize device=cpu image_height="256" image_width="256" interpolation=inter_linear batch_size="1" queue_size="1"]
    yolov5_head_detect_rk [ type=flowunit flowunit=yolov5_head_detect_rk device=rockchip batch_size="1" queue_size="1" core_mask_id="1" ]
    yolov5_head_post [ type=flowunit flowunit=yolov5_head_post device=cpu batch_size="1" queue_size="1"]
    draw_boxes [ type=flowunit flowunit=draw_boxes device=cpu batch_size="1" queue_size="1"]
    video_fps [ type=flowunit flowunit=video_fps device=cpu ]
    #videoencoder [ type=flowunit flowunit=video_encoder device=cpu encoder=mpeg4 format=mp4 default_dest_url="/home/wm/test-video/test-1-result.mp4" ]
    videoencoder [ type=flowunit flowunit=video_out device=rockchip encoder=mpeg4 format=mp4 default_dest_url="/home/wm/test-video/test-1-result.mp4" ]
    #videoencoder [ type=flowunit flowunit=video_out device=rockchip encoder=mpeg4 format=rtsp default_dest_url="rtsp://192.168.3.18:554/test" ]
    output_broker_pre [ type=flowunit flowunit=output_broker_pre device=cpu save_results=false]
    output_broker [ type=flowunit flowunit=output_broker device=cpu retry_count_limit="2", retry_interval_base_ms="100", retry_interval_increment_ms="100", retry_interval_limit_ms="200"]

    video_input:out_video_url -> videodemuxer:in_video_url
    videodemuxer:out_video_packet -> videodecoder:in_video_packet
    videodecoder:out_video_frame -> img_resize:in_image
    img_resize:"out_image" -> yolov5_car_detect_rk:"input"
    yolov5_car_detect_rk:"output" -> yolov5_car_detect_post:"in_feat"
    yolov5_car_detect_rk:"output2" -> yolov5_car_detect_post:"in_feat2"
    yolov5_car_detect_rk:"output3" -> yolov5_car_detect_post:"in_feat3"
    videodecoder:out_video_frame -> yolov5_car_detect_post:"in_image"
    yolov5_car_detect_post:"has_car" -> tracke: "input_data"
    tracke:"output_data" -> expand_car_boxes:"in_data"
    expand_car_boxes:"roi_image" -> car_resize:"in_image"
    car_resize:"out_image" -> yolov5_head_detect_rk:"input"
    yolov5_head_detect_rk:"output" -> yolov5_head_post:"in_feat"
    yolov5_head_detect_rk:"output2" -> yolov5_head_post:"in_feat2"
    yolov5_head_detect_rk:"output3" -> yolov5_head_post:"in_feat3"
    expand_car_boxes:"roi_image" -> yolov5_head_post:"in_image"
    yolov5_head_post:"out_data" -> draw_boxes:"in_head"
    tracke:"output_data" -> draw_boxes:"in_image"
    yolov5_car_detect_post:"no_car" -> video_fps:input_data
    draw_boxes:"out_data" -> video_fps:input_data
    video_fps:out_data -> videoencoder:in_video_frame
    video_fps:"out_data" -> output_broker_pre:"input_data"
    output_broker_pre:"out_event_data" -> output_broker:"in_output_info"

}
\
"""
format = "graphviz"

