[base]
name = "output_broker_pre" # The FlowUnit name 
device = "cpu" # The device the flowunit runs on,cpu,cuda,ascend
version = "1.0.0" # The version of the flowunit
description = "A flowunit for modelbox" # The description of the flowunit
group_type = "generic" # flowunit group attribution 
entry = "output_broker_pre@Output_broker_preFlowUnit" # Python flowunit entry function
type = "python" # Fixed value

[config]
output_broker_config = "/home/wm/code/modelbox-app/car-rk-test/src/flowunit/output_broker_pre/webhook-wxs-config.json"
draw_results = false
save_results = false

# Input ports description
[input]
[input.input1]
name = "input_data"


# Output ports description
[output]
[output.output1]
name = "out_event_data"


